apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cluster-alerts
  namespace: monitoring
spec:
  groups:
  - name: cluster.rules
    rules:

    - alert: HighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total[2m])) > 0.8
      for: 2m
      labels:
        severity: warning
      annotations:
        message: High CPU usage detected

    - alert: PodRestarting
      expr: increase(kube_pod_container_status_restarts_total[10m]) > 3
      for: 1m
      labels:
        severity: critical
      annotations:
        message: Pod restarting frequently
